/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UcapanRouteImport } from './routes/ucapan'
import { Route as IndexRouteImport } from './routes/index'

const UcapanRoute = UcapanRouteImport.update({
  id: '/ucapan',
  path: '/ucapan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ucapan': typeof UcapanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ucapan': typeof UcapanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ucapan': typeof UcapanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ucapan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ucapan'
  id: '__root__' | '/' | '/ucapan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UcapanRoute: typeof UcapanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ucapan': {
      id: '/ucapan'
      path: '/ucapan'
      fullPath: '/ucapan'
      preLoaderRoute: typeof UcapanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UcapanRoute: UcapanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
